name: Node CI
on: [ push, pull_request ]

jobs:
  static-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: npm i

      - name: Format & Lint
        run: npm run check

      - name: Install types-tests dependencies
        run: |
          ( cd types-test/expect-type-tests ; npm i )
          ( cd types-test/jest-all-type-tests ; npm i )
          ( cd types-test/jest-partial-type-tests ; npm i )
          ( cd types-test/vitest-all-type-tests ; npm i )
          ( cd types-test/vitest-partial-type-tests ; npm i )

      - name: Generate types-test test files
        run: npm run setup:types:test

      - name: Test types
        run: npm run types:test

  unittest:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: npm i

      - name: Test
        run: npm run test:unit

  deploy:
    runs-on: ubuntu-22.04
    needs:
      - static-tests
      - unittest

    # Run only on pushing to master
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: npm i

      - name: Release to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Enable npm provenance - (doing here so when we have tests that actually publish to local npm registry they won't fail)
          npm_config_provenance: true
        run: npx semantic-release
